/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_InnerMessageListener */

#ifndef _Included_jni_InnerMessageListener
#define _Included_jni_InnerMessageListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
