/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_InnerNativeMQ */


#ifndef _Included_jni_InnerNativeMQ
#define _Included_jni_InnerNativeMQ
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_InnerNativeMQ
 * Method:    initialize
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    release
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_release
  (JNIEnv *, jobject);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    send
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_send
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    receive
 * Signature: (Ljava/lang/String;Ljava/lang/String;J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jni_InnerNativeMQ_receive
  (JNIEnv *, jobject, jstring, jstring, jlong);


///////////////////////////////////////////////////////////////////////////////////////////
//
// Under this line are not implemented
//
///////////////////////////////////////////////////////////////////////////////////////////
/*
 * Class:     jni_InnerNativeMQ
 * Method:    createMQChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;IILjava/lang/String;)Ljni/InnerMQChannel;
 */
JNIEXPORT jobject JNICALL Java_jni_InnerNativeMQ_createMQChannel
  (JNIEnv *, jobject, jstring, jstring, jint, jint, jstring);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    destroyMQChannel
 * Signature: (Ljni/InnerMQChannel;)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_destroyMQChannel
  (JNIEnv *, jobject, jobject);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    policySend
 * Signature: (Ljni/InnerMQChannel;Ljava/lang/String;JI)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_policySend
  (JNIEnv *, jobject, jobject, jstring, jlong, jint);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    acknowledge
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_acknowledge
  (JNIEnv *, jobject, jstring, jstring, jstring, jlong);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    subscribe
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljni/InnerMessageListener;)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_subscribe
  (JNIEnv *, jobject, jstring, jstring, jobject);

/*
 * Class:     jni_InnerNativeMQ
 * Method:    unsubscribe
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljni/InnerMessageListener;)I
 */
JNIEXPORT jint JNICALL Java_jni_InnerNativeMQ_unsubscribe
  (JNIEnv *, jobject, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
