/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_InnerMQChannel */

#ifndef _Included_jni_InnerMQChannel
#define _Included_jni_InnerMQChannel
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
