#ifndef SYSMGR_SERVER_ALARM_GLOBAL_H
#define SYSMGR_SERVER_ALARM_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYSMGR_SERVER_ALARM_LIBRARY)
#  define SYSMGR_SERVER_ALARMSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYSMGR_SERVER_ALARMSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SYSMGR_SERVER_ALARM_GLOBAL_H
